/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BBreadcrumb: typeof import('bootstrap-vue-next/components/BBreadcrumb')['BBreadcrumb']
    BBreadcrumbItem: typeof import('bootstrap-vue-next/components/BBreadcrumb')['BBreadcrumbItem']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BButtonToolbar: typeof import('bootstrap-vue-next/components/BButton')['BButtonToolbar']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardGroup: typeof import('bootstrap-vue-next/components/BCard')['BCardGroup']
    BCardImg: typeof import('bootstrap-vue-next/components/BCard')['BCardImg']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdownDivider: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormSpinbutton: typeof import('bootstrap-vue-next/components/BFormSpinbutton')['BFormSpinbutton']
    BFormTags: typeof import('bootstrap-vue-next/components/BFormTags')['BFormTags']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
    BPagination: typeof import('bootstrap-vue-next/components/BPagination')['BPagination']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BToastOrchestrator: typeof import('bootstrap-vue-next/components/BToast')['BToastOrchestrator']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Panel: typeof import('primevue/panel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Toast: typeof import('primevue/toast')['default']
    VirtualScroller: typeof import('primevue/virtualscroller')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
